image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - development
  before_script:
    - apt-get update
    - apt-get install -y ssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "cd ~/uat_application/finfi_admin && git pull origin development && npm install && npm run build && pm2 restart uat-app"
